# -*- coding: utf-8 -*-
"""LinearRegression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ojt-b2FTxeoeZulB3BOuASDdoNjTACUd
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('/content/placement.csv')

df

df.head()

plt.scatter(df['cgpa'],df['package'])
plt.xlabel('cgpa')
plt.ylabel('package(in LPA)')

x=df.iloc[:,0:1]
y=df.iloc[:,-1]

y

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train,y_train)

lr.predict(X_test.iloc[0].values.reshape(1,1))

lr.predict(X_test.iloc[5].values.reshape(1,1))

plt.scatter(df['cgpa'],df['package'])
plt.plot(X_train,lr.predict(X_train),color='red')
plt.xlabel('cgpa')
plt.ylabel('package(in LPA)')

m = lr.coef_

b = lr.intercept_

m
b

m

b

X_test

y_test

m*8.58 + b

m*6.93 + b

